{% set name = "parallelproj" %}
{% set version = "1.5.0" %}
{% set build_number = 2 %}

{% if cuda_compiler_version != "None" %}
{% set build_number = build_number + 200 %}
{% endif %}

package:
  name: parallelproj-split
  version: {{ version }}

source:
  url: https://github.com/gschramm/parallelproj/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 761ad311f80f31a673dae9390bc22ed27d0bf0cec7d94117975bcc12441b3090

build:
  number: {{ build_number }}

outputs:
  - name: libparallelproj
    script: build-parallelproj.sh  # [unix]
    script: bld-parallelproj.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libparallelproj') }}
        - libparallelproj =*=cuda*  # [cuda_compiler_version != "None"]
        - libparallelproj =*=cpu*  # [cuda_compiler_version == "None"]
      ignore_run_exports:
        - cudatoolkit
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]


    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}  # [cuda_compiler_version != "None"]
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - cmake >=3.23
        - ninja
        - python
      host:
        - libgomp      # [linux]
        - llvm-openmp  # [osx]
      run:
        - __cuda  # [cuda_compiler_version != "None"]
      run_constrained:
        - parallelproj >=1.3.4  # parallelproj output renamed to libparallelproj
    test:
      commands:
        - test -f $PREFIX/lib/libparallelproj_c$SHLIB_EXT  # [unix]
        - test -f $PREFIX/include/parallelproj_c.h  # [unix]
        - test -f $PREFIX/lib/cmake/parallelproj/parallelprojConfig.cmake  # [unix]
        - test -f $PREFIX/lib/libparallelproj_cuda$SHLIB_EXT  # [linux and cuda_compiler_version != "None"]
        - test -f $PREFIX/include/parallelproj_cuda.h  # [linux and cuda_compiler_version != "None"]
        - if not exist %LIBRARY_LIB%\parallelproj_c.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\parallelproj_c.dll exit 1  # [win]
        - if not exist %LIBRARY_INC%\parallelproj_c.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\cmake\parallelproj\parallelprojConfig.cmake exit 1  # [win]

  - name: parallelproj
    script: build-python.sh  # [unix]
    script: bld-python.bat  # [win]
    build:
      skip: true  # [not linux64]
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ PKG_VERSION }}
    requirements:
      build:
        - python  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - pip
        - setuptools >=45
        - setuptools_scm >=7.0
        - setuptools_scm_git_archive
      run:
        - {{ pin_subpackage('libparallelproj') }}
        - python >=3.8
        - numpy >=1.22
        - matplotlib-base >=3.0
        - array-api-compat
    test:
      requires:
        - pip
        - pytest
        - scipy >=1.0
      imports:
        - parallelproj
      source_files:
        - test/parallelproj/*
      commands:
        - pip check
        - pytest test/parallelproj -vs

about:
  home: https://github.com/gschramm/parallelproj
  license: MIT
  license_file: LICENSE
  summary: parallelized TOF PET projectors

extra:
  recipe-maintainers:
    - gschramm
  feedstock-name: parallelproj
